export const actions = {
  login: 'LOGIN',
  logout: 'LOGOUT',
  setToast: 'SET_TOAST',
  closeToast: 'CLOSE_TOAST',
  getProducts: 'GET_PRODUCTS',
  fetchProductsStart: 'FETCH_PRODUCTS_START',
  fetchProductsSuccess: 'FETCH_PRODUCTS_SUCCESS',
  fetchProductsFailure: 'FETCH_PRODUCTS_FAILURE',
  sortProducts: 'SORT_PRODUCTS',
  togglefastDeliveryOnly: 'TOGGLE_FAST_DELIVERY_ONLY',
  toggleIncludeOutOfStock: 'TOGGLE_INCLUDE_OUT_OF_STOCK',
  toggleProcessors: 'TOGGLE_PROCESSORS',
  setPriceRange: 'SET_PRICE_RANGE',
  setRating: 'SET_RATING',
  setSearch: 'SET_SEARCH',
  resetFilters: 'CLEAR_FILTER',
}
